/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AdditionalInfoType } from './models/AdditionalInfoType';
export { APNAuthenticationEnumType } from './models/APNAuthenticationEnumType';
export type { APNType } from './models/APNType';
export { AttributeEnumType } from './models/AttributeEnumType';
export type { AuthorizationData } from './models/AuthorizationData';
export { AuthorizationStatusEnumType } from './models/AuthorizationStatusEnumType';
export type { BootConfigSchema } from './models/BootConfigSchema';
export type { CertificateHashDataType } from './models/CertificateHashDataType';
export { CertificateSigningUseEnumType } from './models/CertificateSigningUseEnumType';
export type { ChangeAvailabilityRequest } from './models/ChangeAvailabilityRequest';
export { ChangeAvailabilityRequestType } from './models/ChangeAvailabilityRequestType';
export type { ChangeConfigurationRequest } from './models/ChangeConfigurationRequest';
export { ChargingLimitSourceEnumType } from './models/ChargingLimitSourceEnumType';
export type { ChargingProfileCriterionType } from './models/ChargingProfileCriterionType';
export { ChargingProfileKindEnumType } from './models/ChargingProfileKindEnumType';
export { ChargingProfilePurposeEnumType } from './models/ChargingProfilePurposeEnumType';
export type { ChargingProfileType } from './models/ChargingProfileType';
export { ChargingRateUnitEnumType } from './models/ChargingRateUnitEnumType';
export type { ChargingSchedulePeriodType } from './models/ChargingSchedulePeriodType';
export type { ChargingScheduleType } from './models/ChargingScheduleType';
export type { ChargingStationKeyQuerySchema } from './models/ChargingStationKeyQuerySchema';
export type { ChargingStationResponseSchema } from './models/ChargingStationResponseSchema';
export type { ClearChargingProfileType } from './models/ClearChargingProfileType';
export { ComponentCriterionEnumType } from './models/ComponentCriterionEnumType';
export type { ComponentType } from './models/ComponentType';
export type { ComponentVariableType } from './models/ComponentVariableType';
export { ConnectorEnumType } from './models/ConnectorEnumType';
export type { ConsumptionCostType } from './models/ConsumptionCostType';
export { CostKindEnumType } from './models/CostKindEnumType';
export type { CostType } from './models/CostType';
export type { CreateOrUpdateVariableAttributeQuerySchema } from './models/CreateOrUpdateVariableAttributeQuerySchema';
export type { CreateSubscriptionSchema } from './models/CreateSubscriptionSchema';
export type { CustomDataType } from './models/CustomDataType';
export { DataEnumType } from './models/DataEnumType';
export type { EVSEType } from './models/EVSEType';
export type { FirmwareType } from './models/FirmwareType';
export { GetCertificateIdUseEnumType } from './models/GetCertificateIdUseEnumType';
export type { GetConfigurationRequest } from './models/GetConfigurationRequest';
export type { GetVariableDataType } from './models/GetVariableDataType';
export { HashAlgorithmEnumType } from './models/HashAlgorithmEnumType';
export { IdTokenEnumType } from './models/IdTokenEnumType';
export type { IdTokenInfoType } from './models/IdTokenInfoType';
export type { IdTokenKeyQuerySchema } from './models/IdTokenKeyQuerySchema';
export type { IdTokenResponse } from './models/IdTokenResponse';
export type { IdTokenType } from './models/IdTokenType';
export { InstallCertificateUseEnumType } from './models/InstallCertificateUseEnumType';
export type { LocationKeyQuerySchema } from './models/LocationKeyQuerySchema';
export type { LocationResponseSchema } from './models/LocationResponseSchema';
export { LogEnumType } from './models/LogEnumType';
export type { LogParametersType } from './models/LogParametersType';
export type { MessageConfirmationSchema } from './models/MessageConfirmationSchema';
export type { MessageConfirmationSchemaArray } from './models/MessageConfirmationSchemaArray';
export type { MessageContentType } from './models/MessageContentType';
export { MessageFormatEnumType } from './models/MessageFormatEnumType';
export type { MessageInfoType } from './models/MessageInfoType';
export { MessagePriorityEnumType } from './models/MessagePriorityEnumType';
export type { MessageQuerystring } from './models/MessageQuerystring';
export { MessageStateEnumType } from './models/MessageStateEnumType';
export { MessageTriggerEnumType } from './models/MessageTriggerEnumType';
export type { ModelKeyQuerystringSchema } from './models/ModelKeyQuerystringSchema';
export { MonitorEnumType } from './models/MonitorEnumType';
export { MonitoringBaseEnumType } from './models/MonitoringBaseEnumType';
export { MonitoringCriterionEnumType } from './models/MonitoringCriterionEnumType';
export { MutabilityEnumType } from './models/MutabilityEnumType';
export type { NetworkConnectionProfileType } from './models/NetworkConnectionProfileType';
export type { NetworkProfileDeleteQuerySchema } from './models/NetworkProfileDeleteQuerySchema';
export type { NetworkProfileQuerySchema } from './models/NetworkProfileQuerySchema';
export type { ocpp2_0_1_CancelReservationRequest } from './models/ocpp2_0_1_CancelReservationRequest';
export type { ocpp2_0_1_CertificateSignedRequest } from './models/ocpp2_0_1_CertificateSignedRequest';
export type { ocpp2_0_1_ChangeAvailabilityRequest } from './models/ocpp2_0_1_ChangeAvailabilityRequest';
export type { ocpp2_0_1_ClearCacheRequest } from './models/ocpp2_0_1_ClearCacheRequest';
export type { ocpp2_0_1_ClearChargingProfileRequest } from './models/ocpp2_0_1_ClearChargingProfileRequest';
export type { ocpp2_0_1_ClearDisplayMessageRequest } from './models/ocpp2_0_1_ClearDisplayMessageRequest';
export type { ocpp2_0_1_ClearedChargingLimitRequest } from './models/ocpp2_0_1_ClearedChargingLimitRequest';
export type { ocpp2_0_1_ClearVariableMonitoringRequest } from './models/ocpp2_0_1_ClearVariableMonitoringRequest';
export type { ocpp2_0_1_CostUpdatedRequest } from './models/ocpp2_0_1_CostUpdatedRequest';
export type { ocpp2_0_1_CustomerInformationRequest } from './models/ocpp2_0_1_CustomerInformationRequest';
export type { ocpp2_0_1_DeleteCertificateRequest } from './models/ocpp2_0_1_DeleteCertificateRequest';
export type { ocpp2_0_1_GenerateCertificateChainSchema } from './models/ocpp2_0_1_GenerateCertificateChainSchema';
export type { ocpp2_0_1_GetBaseReportRequest } from './models/ocpp2_0_1_GetBaseReportRequest';
export type { ocpp2_0_1_GetChargingProfilesRequest } from './models/ocpp2_0_1_GetChargingProfilesRequest';
export type { ocpp2_0_1_GetCompositeScheduleRequest } from './models/ocpp2_0_1_GetCompositeScheduleRequest';
export type { ocpp2_0_1_GetDisplayMessagesRequest } from './models/ocpp2_0_1_GetDisplayMessagesRequest';
export type { ocpp2_0_1_GetInstalledCertificateIdsRequest } from './models/ocpp2_0_1_GetInstalledCertificateIdsRequest';
export type { ocpp2_0_1_GetLocalListVersionRequest } from './models/ocpp2_0_1_GetLocalListVersionRequest';
export type { ocpp2_0_1_GetLogRequest } from './models/ocpp2_0_1_GetLogRequest';
export type { ocpp2_0_1_GetMonitoringReportRequest } from './models/ocpp2_0_1_GetMonitoringReportRequest';
export type { ocpp2_0_1_GetReportRequest } from './models/ocpp2_0_1_GetReportRequest';
export type { ocpp2_0_1_GetTransactionStatusRequest } from './models/ocpp2_0_1_GetTransactionStatusRequest';
export type { ocpp2_0_1_GetVariablesRequest } from './models/ocpp2_0_1_GetVariablesRequest';
export type { ocpp2_0_1_InstallCertificateRequest } from './models/ocpp2_0_1_InstallCertificateRequest';
export type { ocpp2_0_1_InstallRootCertificateSchema } from './models/ocpp2_0_1_InstallRootCertificateSchema';
export type { ocpp2_0_1_PublishFirmwareRequest } from './models/ocpp2_0_1_PublishFirmwareRequest';
export type { ocpp2_0_1_RequestStartTransactionRequest } from './models/ocpp2_0_1_RequestStartTransactionRequest';
export type { ocpp2_0_1_RequestStopTransactionRequest } from './models/ocpp2_0_1_RequestStopTransactionRequest';
export type { ocpp2_0_1_ReserveNowRequest } from './models/ocpp2_0_1_ReserveNowRequest';
export type { ocpp2_0_1_ResetRequest } from './models/ocpp2_0_1_ResetRequest';
export type { ocpp2_0_1_SendLocalListRequest } from './models/ocpp2_0_1_SendLocalListRequest';
export type { ocpp2_0_1_SetChargingProfileRequest } from './models/ocpp2_0_1_SetChargingProfileRequest';
export type { ocpp2_0_1_SetDisplayMessageRequest } from './models/ocpp2_0_1_SetDisplayMessageRequest';
export type { ocpp2_0_1_SetMonitoringBaseRequest } from './models/ocpp2_0_1_SetMonitoringBaseRequest';
export type { ocpp2_0_1_SetMonitoringLevelRequest } from './models/ocpp2_0_1_SetMonitoringLevelRequest';
export type { ocpp2_0_1_SetNetworkProfileRequest } from './models/ocpp2_0_1_SetNetworkProfileRequest';
export type { ocpp2_0_1_SetVariableMonitoringRequest } from './models/ocpp2_0_1_SetVariableMonitoringRequest';
export type { ocpp2_0_1_SetVariablesRequest } from './models/ocpp2_0_1_SetVariablesRequest';
export type { ocpp2_0_1_SystemConfigSchema } from './models/ocpp2_0_1_SystemConfigSchema';
export type { ocpp2_0_1_TlsCertificateSchema } from './models/ocpp2_0_1_TlsCertificateSchema';
export type { ocpp2_0_1_TriggerMessageRequest } from './models/ocpp2_0_1_TriggerMessageRequest';
export type { ocpp2_0_1_UnlockConnectorRequest } from './models/ocpp2_0_1_UnlockConnectorRequest';
export type { ocpp2_0_1_UnpublishFirmwareRequest } from './models/ocpp2_0_1_UnpublishFirmwareRequest';
export type { ocpp2_0_1_UpdateFirmwareRequest } from './models/ocpp2_0_1_UpdateFirmwareRequest';
export { OCPPInterfaceEnumType } from './models/OCPPInterfaceEnumType';
export { OCPPTransportEnumType } from './models/OCPPTransportEnumType';
export { OCPPVersionEnumType } from './models/OCPPVersionEnumType';
export { OperationalStatusEnumType } from './models/OperationalStatusEnumType';
export type { processPaymentSchema } from './models/processPaymentSchema';
export { RecurrencyKindEnumType } from './models/RecurrencyKindEnumType';
export { RegistrationStatusEnumType } from './models/RegistrationStatusEnumType';
export type { RelativeTimeIntervalType } from './models/RelativeTimeIntervalType';
export type { RemoteStartTransactionRequest } from './models/RemoteStartTransactionRequest';
export { RemoteStartTransactionRequestChargingProfileKind } from './models/RemoteStartTransactionRequestChargingProfileKind';
export { RemoteStartTransactionRequestChargingProfilePurpose } from './models/RemoteStartTransactionRequestChargingProfilePurpose';
export { RemoteStartTransactionRequestChargingRateUnit } from './models/RemoteStartTransactionRequestChargingRateUnit';
export { RemoteStartTransactionRequestRecurrencyKind } from './models/RemoteStartTransactionRequestRecurrencyKind';
export type { RemoteStopTransactionRequest } from './models/RemoteStopTransactionRequest';
export { ReportBaseEnumType } from './models/ReportBaseEnumType';
export type { ReportDataTypeSchema } from './models/ReportDataTypeSchema';
export { ResetEnumType } from './models/ResetEnumType';
export type { ResetRequest } from './models/ResetRequest';
export { ResetRequestType } from './models/ResetRequestType';
export type { SalesTariffEntryType } from './models/SalesTariffEntryType';
export type { SalesTariffType } from './models/SalesTariffType';
export type { SetMonitoringDataType } from './models/SetMonitoringDataType';
export type { SetVariableDataType } from './models/SetVariableDataType';
export type { StatusInfoType } from './models/StatusInfoType';
export { SystemConfigSchema } from './models/SystemConfigSchema';
export type { TariffQuerySchema } from './models/TariffQuerySchema';
export type { TariffResponseSchema } from './models/TariffResponseSchema';
export type { TariffSchema } from './models/TariffSchema';
export type { TenantQuerySchema } from './models/TenantQuerySchema';
export type { TransactionEventQuerySchema } from './models/TransactionEventQuerySchema';
export type { TransactionEventResponseSchema } from './models/TransactionEventResponseSchema';
export type { TransactionEventsQuerySchema } from './models/TransactionEventsQuerySchema';
export type { TransactionEventsResponseSchema } from './models/TransactionEventsResponseSchema';
export type { TriggerMessageRequest } from './models/TriggerMessageRequest';
export { TriggerMessageRequestRequestedMessage } from './models/TriggerMessageRequestRequestedMessage';
export type { UpdateChargingStationPasswordQuerySchema } from './models/UpdateChargingStationPasswordQuerySchema';
export type { UpdateChargingStationPasswordRequestSchema } from './models/UpdateChargingStationPasswordRequestSchema';
export { UpdateEnumType } from './models/UpdateEnumType';
export type { UpdateFirmwareRequest } from './models/UpdateFirmwareRequest';
export type { UpdateTlsCertificateQuerySchema } from './models/UpdateTlsCertificateQuerySchema';
export type { VariableAttributeQuerySchema } from './models/VariableAttributeQuerySchema';
export type { VariableAttributeType } from './models/VariableAttributeType';
export type { VariableCharacteristicsType } from './models/VariableCharacteristicsType';
export type { VariableType } from './models/VariableType';
export { VPNEnumType } from './models/VPNEnumType';
export type { VPNType } from './models/VPNType';
export type { WebsocketDeleteQuerySchema } from './models/WebsocketDeleteQuerySchema';
export type { WebsocketGetQuerySchema } from './models/WebsocketGetQuerySchema';
export type { WebsocketRequestSchema } from './models/WebsocketRequestSchema';

export { CertificatesService } from './services/CertificatesService';
export { ConfigurationService } from './services/ConfigurationService';
export { EvdriverService } from './services/EvdriverService';
export { MonitoringService } from './services/MonitoringService';
export { OcpprouterService } from './services/OcpprouterService';
export { ReportingService } from './services/ReportingService';
export { SmartchargingService } from './services/SmartchargingService';
export { TransactionsService } from './services/TransactionsService';
